---
- name: install docker
  hosts: all
  sudo: yes
  tasks:
    - name: Downloading and enable the EPEL repository definitions.
      action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

    - name: install libselinux
      yum: pkg=libselinux-python state=present

    - name: Install Python pip
      yum: pkg=python-pip state=present
      
    - include: tasks/install_docker.yml
    - include: tasks/consul_registrar_install.yml
    - include: tasks/load_balancer.yml
    - include: tasks/build_spring_boot.yml
